services:
  - type: web
    name: exte-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run prisma:generate
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: exte-backend-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
